;              
CREATE USER IF NOT EXISTS ROOT SALT '3a1148db295d6419' HASH '618ce9309273504534c3b0f01ffd527b52f86048304010c8867bbd62f2c38dc1' ADMIN;          
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.HOMESTAY(
    ID VARCHAR(20) NOT NULL,
    PEMILIK VARCHAR(20) DEFAULT NULL,
    LOKASI VARCHAR(4) DEFAULT NULL,
    JML_KAMAR INT DEFAULT NULL,
    JML_BED INT DEFAULT NULL,
    JML_WC INT DEFAULT NULL
);       
ALTER TABLE PUBLIC.HOMESTAY ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HOMESTAY; 
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.EVENT(
    ID VARCHAR(10) NOT NULL,
    NAMA_EVENT VARCHAR(45) DEFAULT NULL,
    PENYELENGGARA VARCHAR(45) DEFAULT NULL,
    MULAI_EVENT VARCHAR(8) DEFAULT NULL,
    SELESAI_EVENT VARCHAR(8) DEFAULT NULL
);      
ALTER TABLE PUBLIC.EVENT ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_3 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENT;    
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.PENYEWA(
    ID VARCHAR(20) NOT NULL,
    NAMA VARCHAR(45) DEFAULT NULL,
    JNS_KELAMIN VARCHAR(1) DEFAULT NULL,
    ALAMAT VARCHAR(50) DEFAULT NULL,
    NO_TELP VARCHAR(20) DEFAULT NULL,
    JNS_MAKANAN VARCHAR(10) DEFAULT NULL,
    KETERANGAN VARCHAR(20) DEFAULT NULL,
    ID_HS VARCHAR(20) DEFAULT NULL,
    ID_EVT VARCHAR(10) DEFAULT NULL
);          
ALTER TABLE PUBLIC.PENYEWA ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_2 PRIMARY KEY(ID); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PENYEWA;  
CREATE CACHED TABLE IF NOT EXISTS PUBLIC.PENGGUNA(
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    ROLE VARCHAR2(1) NOT NULL
);  
ALTER TABLE PUBLIC.PENGGUNA ADD CONSTRAINT IF NOT EXISTS PUBLIC.CONSTRAINT_4 PRIMARY KEY(USERNAME);          
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PENGGUNA; 
MERGE INTO PUBLIC.PENGGUNA(USERNAME, PASSWORD, ROLE) VALUES
('admin', 'admin', 'S');          
ALTER TABLE PUBLIC.PENYEWA ADD CONSTRAINT IF NOT EXISTS PUBLIC.ID_EVT_FK FOREIGN KEY(ID_EVT) REFERENCES PUBLIC.EVENT(ID) ON DELETE CASCADE ON UPDATE SET NULL NOCHECK;       
ALTER TABLE PUBLIC.PENYEWA ADD CONSTRAINT IF NOT EXISTS PUBLIC.ID_HS_FK FOREIGN KEY(ID_HS) REFERENCES PUBLIC.HOMESTAY(ID) ON DELETE CASCADE ON UPDATE SET NULL NOCHECK;      
